### ISSUE TITLE
运行main.py时找不到abi

### ISSUE THREAD

**Issue by chenlizhi1205** [iammcy/BFLC-demo#51]
找不到abo的地址
![Uploading 91cdd90803bf1a06c155dd08cf9375c.png…]()

**Comment by chenlizhi1205** [comment]
![Uploading 91cdd90803bf1a06c155dd08cf9375c.png…]()

**Comment by chenlizhi1205** [comment]
2024-05-22 16:23:46.050939: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /home/h3c/miniconda3/envs/BFLC/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
INFO >> compile with nodejs compiler
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/usr/share/nodejs/yargs/lib/argsert.js:67:9)
    at parsed.optional.forEach (/usr/share/nodejs/yargs/lib/argsert.js:49:39)
    at Array.forEach (<anonymous>)
    at argsert (/usr/share/nodejs/yargs/lib/argsert.js:44:21)
    at Object.version (/usr/share/nodejs/yargs/yargs.js:857:5)
    at Object.<anonymous> (/home/h3c/clz/BFLC/python-sdk-master/solcjs:46:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    data_parser.load_abi_file(abi_file)
  File "/home/h3c/clz/BFLC/python-sdk-master/client/datatype_parser.py", line 60, in load_abi_file
    with open(abi_file, 'r') as load_f:
FileNotFoundError: [Errno 2] No such file or directory: 'contracts/CommitteePrecompiled.abi'

**Comment by xinruiya** [comment]
你好，这个abi文件找到了吗，我也是说找不到abi文件
